#!/bin/bash

# 📋 NL2SQL 服务联通性测试 - 使用说明
# 这个文件包含所有可用的测试命令

echo "╔════════════════════════════════════════════════════════╗"
echo "║     NL2SQL 服务联通性测试 - 快速命令参考             ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 选择你要执行的测试方式:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  后端完整测试（推荐）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # 方式A: 直接运行脚本"
echo "  .venv/bin/python test_connectivity.py"
echo ""
echo "  # 方式B: 使用启动脚本"
echo "  ./run_connectivity_tests.sh"
echo ""
echo "  # 方式C: 在Python中运行"
echo "  python3 << 'EOF'"
echo "  from app import create_app"
echo "  from app.services.supabase_client import get_supabase_client"
echo "  from app.services.query_executor import QueryExecutor"
echo ""
echo "  app = create_app()"
echo "  sb = get_supabase_client()"
echo "  executor = QueryExecutor(sb)"
echo "  print('✅ 所有组件初始化成功')"
echo "  EOF"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  前端完整测试"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # 在浏览器控制台 (F12) 中运行:"
echo "  TestConnectivity.runAllTests()"
echo ""
echo "  # 或运行单项测试:"
echo "  TestConnectivity.testBackendHealth()"
echo "  TestConnectivity.testNL2SQLConversion()"
echo "  TestConnectivity.testDatabaseQuery()"
echo "  TestConnectivity.testCORS()"
echo "  TestConnectivity.testNetworkLatency()"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  快速诊断测试"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # 测试后端是否运行"
echo "  curl http://localhost:5000/api/query/health"
echo ""
echo "  # 测试Supabase连接"
echo "  .venv/bin/python -c \\"
echo "  from app.services.supabase_client import get_supabase_client; \\
echo "  print('✅ Connected' if get_supabase_client() else '❌ Failed')\""
echo ""
echo "  # 测试NL2SQL转换"
echo "  curl -X POST http://localhost:5000/api/query/nl-to-sql \\\\"
echo "    -H 'Content-Type: application/json' \\\\"
echo "    -d '{\"natural_language\": \"查询wafers表\"}'"
echo ""
echo "  # 测试数据库查询"
echo "  curl -X POST http://localhost:5000/api/query/execute \\\\"
echo "    -H 'Content-Type: application/json' \\\\"
echo "    -d '{\"sql\": \"SELECT * FROM wafers LIMIT 5\"}'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  可视化仪表板"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # 方式A: 直接打开HTML文件（最简单）"
echo "  open test_connectivity_dashboard.html"
echo ""
echo "  # 方式B: 通过本地Web服务器"
echo "  python -m http.server 8000"
echo "  # 然后访问: http://localhost:8000/test_connectivity_dashboard.html"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5️⃣  查看文档"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # 快速参考"
echo "  cat CONNECTIVITY_TEST_QUICK_REF.md"
echo ""
echo "  # 详细指南"
echo "  cat CONNECTIVITY_TEST_GUIDE.md"
echo ""
echo "  # 测试总结"
echo "  cat CONNECTIVITY_TEST_SUMMARY.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 预期结果"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 后端服务健康检查     PASS"
echo "✅ Supabase连接测试     PASS"
echo "✅ NL2SQL端点测试       PASS"
echo "✅ 查询执行测试         PASS"
echo "✅ 前后端通信测试       PASS"
echo "✅ CORS配置测试         PASS"
echo "✅ 网络性能测试         PASS"
echo ""
echo "总体通过率: 7/7 (100%)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 常见问题快速解决"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ 连接被拒绝"
echo "   → 启动后端: python run.py"
echo ""
echo "❌ Supabase连接失败"
echo "   → 检查 .env 文件中的 SUPABASE_URL 和 SUPABASE_KEY"
echo ""
echo "❌ CORS错误"
echo "   → 确保在 app/__init__.py 中启用了 CORS"
echo ""
echo "❌ 网络超时"
echo "   → 检查网络连接: ping 8.8.8.8"
echo "   → 检查 Supabase 服务状态"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 建议"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 定期运行测试（部署前、每周一次等）"
echo "2. 保存测试报告用于对比"
echo "3. 设置自动化测试（CI/CD）"
echo "4. 监控性能指标变化"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║        更多信息请查看相关文档文件                    ║"
echo "╚════════════════════════════════════════════════════════╝"
